package com.xworkz.desert.runner;

import com.xworkz.desert.dto.DesertDTO;
import com.xworkz.desert.repo.DesertRepo;
import com.xworkz.desert.repo.DesertRepoImpl;
import com.xworkz.desert.service.DesertService;
import com.xworkz.desert.service.DesertServiceimpl;

public class DesertRunner {

	public static void main(String[] args) {
		DesertDTO desertDTO = new DesertDTO(1, "sahara desert", "north africa", "libya", 34, 45);
		DesertRepo repo = new DesertRepoImpl();
		DesertService service = new DesertServiceimpl(repo);
		boolean save = service.validAndSave(desertDTO);
		System.out.println("saved:" + save);
		System.out.println("    ");
		DesertDTO desertDTO1 = new DesertDTO(2, "atacama desert", "west of andes", "peru", 34, 45);
		DesertService service1 = new DesertServiceimpl(repo);
		boolean save1 = service1.validAndSave(desertDTO1);
		System.out.println("saved:" + save1);
		System.out.println("    ");
		DesertDTO desertDTO2 = new DesertDTO(3, "gobi desert", "east asia", "china", 34, 45);
		DesertService service2 = new DesertServiceimpl(repo);
		boolean save2 = service2.validAndSave(desertDTO2);
		System.out.println("saved:" + save2);
		System.out.println("    ");
		DesertDTO desertDTO3 = new DesertDTO(4, "kalahari desert", "south africa", "ladakh", 34, 45);
		DesertService service3 = new DesertServiceimpl(repo);
		boolean save3 = service3.validAndSave(desertDTO3);
		System.out.println("saved:" + save3);
		System.out.println("    ");
		DesertDTO desertDTO4 = new DesertDTO(5, "arabian desert", "eurasia", "arabian", 34, 45);
		DesertService service4 = new DesertServiceimpl(repo);
		boolean save4 = service4.validAndSave(desertDTO4);
		System.out.println("saved:" + save4);
		System.out.println("    ");
		DesertDTO desertDTO5 = new DesertDTO(6, "namib desert", "africa", "atlantic coast", 34, 45);
		DesertService service5 = new DesertServiceimpl(repo);
		boolean save5 = service5.validAndSave(desertDTO5);
		System.out.println("saved:" + save5);
		System.out.println("    ");
		DesertDTO desertDTO6 = new DesertDTO(7, "mojave desert", "southwestern US", "southeastern califonia", 34, 45);
		DesertService service6 = new DesertServiceimpl(repo);
		boolean save6 = service6.validAndSave(desertDTO6);
		System.out.println("saved:" + save6);
		System.out.println("    ");
		DesertDTO desertDTO7 = new DesertDTO(8, "sonoran desert", "arizona", "california", 34, 45);
		DesertService service7 = new DesertServiceimpl(repo);
		boolean save7 = service7.validAndSave(desertDTO7);
		System.out.println("saved:" + save7);
		System.out.println("    ");
		DesertDTO desertDTO8 = new DesertDTO(9, "patagonian desert", "argentina", "south america", 34, 45);
		DesertService service8 = new DesertServiceimpl(repo);
		boolean save8 = service8.validAndSave(desertDTO8);
		System.out.println("saved:" + save8);
		System.out.println("    ");
		DesertDTO desertDTO9 = new DesertDTO(10, "thar desert", "rajasthan", "rajastan", 34, 45);
		DesertService service9 = new DesertServiceimpl(repo);
		boolean save9 = service9.validAndSave(desertDTO9);
		System.out.println("saved:" + save9);
		System.out.println("    ");
		DesertDTO desertDTO10 = new DesertDTO(11, "antartica", "antartica", "artic", 34, 45);
		DesertService service10 = new DesertServiceimpl(repo);
		boolean save10 = service10.validAndSave(desertDTO10);
		System.out.println("saved:" + save10);
		System.out.println("    ");
		DesertDTO desertDTO11 = new DesertDTO(12, "chihuahuan desert", "north america", "america", 34, 45);
		DesertService service11 = new DesertServiceimpl(repo);
		boolean save11 = service11.validAndSave(desertDTO11);
		System.out.println("saved:" + save11);
		System.out.println("    ");
		DesertDTO desertDTO12 = new DesertDTO(13, "taklamakan desert", "xinjiang uygur", "china", 34, 45);
		DesertService service12 = new DesertServiceimpl(repo);
		boolean save12 = service12.validAndSave(desertDTO12);
		System.out.println("saved:" + save12);
		System.out.println("    ");
		DesertDTO desertDTO13 = new DesertDTO(14, "great victoria desert", "australia", "australia", 34, 45);
		DesertService service13 = new DesertServiceimpl(repo);
		boolean save13 = service13.validAndSave(desertDTO13);
		System.out.println("saved:" + save13);
		System.out.println("    ");
		DesertDTO desertDTO14 = new DesertDTO(15, "syrian desert", "arabian", "syria", 34, 45);
		DesertService service14 = new DesertServiceimpl(repo);
		boolean save14 = service14.validAndSave(desertDTO14);
		System.out.println("saved:" + save14);
		System.out.println("    ");
		DesertDTO desertDTO15 = new DesertDTO(16, "karakum desert", "central asia", "asia", 34, 45);
		DesertService service15 = new DesertServiceimpl(repo);
		boolean save15 = service15.validAndSave(desertDTO15);
		System.out.println("saved:" + save15);
		System.out.println("    ");
		DesertDTO desertDTO16 = new DesertDTO(17, "great basin desert", "USA", "sierra nevada", 34, 45);
		DesertService service16 = new DesertServiceimpl(repo);
		boolean save16 = service16.validAndSave(desertDTO16);
		System.out.println("saved:" + save16);
		System.out.println("    ");
		DesertDTO desertDTO17 = new DesertDTO(18, "polar desert", "northern polar region", "earth", 34, 45);
		DesertService service17 = new DesertServiceimpl(repo);
		boolean save17 = service17.validAndSave(desertDTO17);
		System.out.println("saved:" + save17);
		System.out.println("    ");
		DesertDTO desertDTO18 = new DesertDTO(19, "empty quarter desert", "saudi", "oman", 34, 45);
		DesertService service18 = new DesertServiceimpl(repo);
		boolean save18 = service18.validAndSave(desertDTO18);
		System.out.println("saved:" + save4);
		System.out.println("    ");
		DesertDTO desertDTO19 = new DesertDTO(20, "kyzylkum desert", "central asia", "asia", 34, 45);
		DesertService service19 = new DesertServiceimpl(repo);
		boolean save19 = service19.validAndSave(desertDTO19);
		System.out.println("saved:" + save19);
		System.out.println("    ");
		DesertDTO desertDTO20 = new DesertDTO(21, "sandy desert", "australia", "australia", 34, 45);
		DesertService service20 = new DesertServiceimpl(repo);
		boolean save20 = service20.validAndSave(desertDTO20);
		System.out.println("saved:" + save20);
		System.out.println("    ");
		DesertDTO desertDTO21 = new DesertDTO(22, "dasht-e lut", "afghanistan", "afghanistan", 34, 45);
		DesertService service21 = new DesertServiceimpl(repo);
		boolean save21 = service21.validAndSave(desertDTO21);
		System.out.println("saved:" + save21);
		System.out.println("    ");
		DesertDTO desertDTO22 = new DesertDTO(23, "great basin desert", "USA", "sierra nevada", 34, 45);
		DesertService service22 = new DesertServiceimpl(repo);
		boolean save22 = service22.validAndSave(desertDTO22);
		System.out.println("saved:" + save22);
		System.out.println("    ");
		DesertDTO desertDTO23 = new DesertDTO(24, "ghhgvh", "vjhvgf", "hgjgy", 34, 45);
		DesertService service23 = new DesertServiceimpl(repo);
		boolean save23 = service23.validAndSave(desertDTO23);
		System.out.println("saved:" + save23);
		System.out.println("    ");

	}

}
