package com.xworkz.invisible.boot;

import java.util.ArrayList;
import java.util.Collection;
import java.util.LinkedList;
import java.util.List;
import java.util.Set;
import java.util.stream.Stream;

import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

import com.xworkz.invisible.configuration.SpringConfiguration;
import com.xworkz.invisible.thing.Animal;
import com.xworkz.invisible.thing.Bicycle;
import com.xworkz.invisible.thing.Bird;
import com.xworkz.invisible.thing.Bottel;
import com.xworkz.invisible.thing.Charger;
import com.xworkz.invisible.thing.Exam;
import com.xworkz.invisible.thing.Flower;
import com.xworkz.invisible.thing.Function;
import com.xworkz.invisible.thing.Glass;
import com.xworkz.invisible.thing.HandBag;
import com.xworkz.invisible.thing.Oil;
import com.xworkz.invisible.thing.Pets;
import com.xworkz.invisible.thing.Sim;

public class Runner {
	public static void main(String[] args) {
		ApplicationContext spring = new AnnotationConfigApplicationContext(SpringConfiguration.class);
		int counts = spring.getBeanDefinitionCount();
		System.out.println("bean count: " + counts);
		String[] beans = spring.getBeanDefinitionNames();
		Stream.of(beans).forEach(System.out::println);
		System.out.println("*********************STRING***********************    ");
		String name = spring.getBean("name", String.class);
		System.out.println("name:" + name);
		String address = spring.getBean("address", String.class);
		System.out.println("address:" + address);
		String location = spring.getBean("location", String.class);
		System.out.println("location:" + location);
		String flowername = spring.getBean("flowername", String.class);
		System.out.println("flowername:" + flowername);
		String fruitname = spring.getBean("fruitname", String.class);
		System.out.println("fruitname:" + fruitname);
		String temple = spring.getBean("temple", String.class);
		System.out.println("temple:" + temple);
		String forest = spring.getBean("forest", String.class);
		System.out.println("forest:" + forest);
		String city = spring.getBean("city", String.class);
		System.out.println("city:" + city);
		String district = spring.getBean("district", String.class);
		System.out.println("district:" + district);
		String country = spring.getBean("country", String.class);
		System.out.println("country:" + country);
		String taluk = spring.getBean("taluk", String.class);
		System.out.println("taluk:" + taluk);
		String capital = spring.getBean("capital", String.class);
		System.out.println("capital:" + capital);
		String watch = spring.getBean("watch", String.class);
		System.out.println("watch:" + watch);
		System.out.println("************COLLECTION***********************      ");
		List drink = spring.getBean("drink", List.class);
		System.out.println("drink:" + drink);
		ArrayList god = spring.getBean("god", ArrayList.class);
		System.out.println("god:" + god);
		Set rosecolors = spring.getBean("rosecolors", Set.class);
		System.out.println("rosecolors:" + rosecolors);
		Collection snack = spring.getBean("snack", Collection.class);
		System.out.println("snack:" + snack);
		LinkedList festival = spring.getBean("festival", LinkedList.class);
		System.out.println("festival:" + festival);
		System.out.println("***********************INTEGER********************      ");
		int rollno = spring.getBean("rollNo", int.class);
		System.out.println("rollno:" + rollno);
		int age = spring.getBean("age", int.class);
		System.out.println("age:" + age);
		int kg = spring.getBean("kg", int.class);
		System.out.println("kg:" + kg);
		int seatno = spring.getBean("seatno", int.class);
		System.out.println("seatno:" + seatno);
		int beanches = spring.getBean("beanches", int.class);
		System.out.println("beanches:" + beanches);
		int seats = spring.getBean("seats", int.class);
		System.out.println("seats:" + seats);
		int homes = spring.getBean("homes", int.class);
		System.out.println("homes:" + homes);
		int trains = spring.getBean("trains", int.class);
		System.out.println("trains:" + trains);
		int bus = spring.getBean("bus", int.class);
		System.out.println("bus:" + bus);
		System.out.println("****************BOOLEAN**************            ");
		boolean well = spring.getBean("well", boolean.class);
		System.out.println("well:" + well);
		boolean hungry = spring.getBean("hungry", boolean.class);
		System.out.println("hungry:" + hungry);
		boolean angry = spring.getBean("angry", boolean.class);
		System.out.println("angry:" + angry);
		boolean coming = spring.getBean("coming", boolean.class);
		System.out.println("coming:" + coming);
		boolean guilty = spring.getBean("guilty", boolean.class);
		System.out.println("guilty:" + guilty);
		boolean ironed = spring.getBean("ironed", boolean.class);
		System.out.println("ironed:" + ironed);
		boolean arrived = spring.getBean("arrived", boolean.class);
		System.out.println("arrived:" + arrived);
		boolean departed = spring.getBean("departed", boolean.class);
		System.out.println("departed:" + departed);
		boolean absent = spring.getBean("absent", boolean.class);
		System.out.println("absent:" + absent);
		System.out.println("***************DOUBLE*********************                    ");
		double length = spring.getBean("length", double.class);
		System.out.println("length:" + length);
		double weight = spring.getBean("weight", double.class);
		System.out.println("weight:" + weight);
		double breadth = spring.getBean("breadth", double.class);
		System.out.println("breadth:" + breadth);
		double shoesize = spring.getBean("shoesize", double.class);
		System.out.println("shoesize:" + shoesize);
		double pantsize = spring.getBean("pantsize", double.class);
		System.out.println("pantsize:" + pantsize);
		double shirtsize = spring.getBean("shirtsize", double.class);
		System.out.println("shirtsize:" + shirtsize);
		double slipperSize = spring.getBean("slipperSize", double.class);
		System.out.println("slipperSize:" + slipperSize);
		double grams = spring.getBean("grams", double.class);
		System.out.println("grams:" + grams);
		double volume = spring.getBean("volume", double.class);
		System.out.println("volume:" + volume);
		System.out.println("******************LONG********************       ");
		long phoneno = spring.getBean("phoneno", long.class);
		System.out.println("phonenumber:" + phoneno);
		long phoneno1 = spring.getBean("phoneno1", long.class);
		System.out.println("phonenumber:" + phoneno1);
		long phoneno2 = spring.getBean("phoneno2", long.class);
		System.out.println("phonenumber:" + phoneno2);
		long phoneno3 = spring.getBean("phoneno3", long.class);
		System.out.println("phonenumber:" + phoneno3);
		long phoneno4 = spring.getBean("phoneno4", long.class);
		System.out.println("phonenumber:" + phoneno4);
		long phoneno5 = spring.getBean("phoneno5", long.class);
		System.out.println("phonenumber:" + phoneno5);
		long phoneno6 = spring.getBean("phoneno6", long.class);
		System.out.println("phonenumber:" + phoneno6);
		long phoneno7 = spring.getBean("phoneno7", long.class);
		System.out.println("phonenumber:" + phoneno7);
		long phoneno8 = spring.getBean("phoneno8", long.class);
		System.out.println("phonenumber:" + phoneno8);
		System.out.println("****************SHORT*****************        ");
		short price = spring.getBean("price", short.class);
		System.out.println("price:" + price);
		short price1 = spring.getBean("price1", short.class);
		System.out.println("price:" + price1);
		short price2 = spring.getBean("price2", short.class);
		System.out.println("price:" + price2);
		short price3 = spring.getBean("price3", short.class);
		System.out.println("price:" + price3);
		short price4 = spring.getBean("price4", short.class);
		System.out.println("price:" + price4);
		short price5 = spring.getBean("price5", short.class);
		System.out.println("price:" + price5);
		short price6 = spring.getBean("price6", short.class);
		System.out.println("price:" + price6);
		short price7 = spring.getBean("price7", short.class);
		System.out.println("price:" + price7);
		short price8 = spring.getBean("price8", short.class);
		System.out.println("price:" + price8);
		System.out.println("******************************FLOAT****************       ");
		float points = spring.getBean("points", float.class);
		System.out.println("points:" + points);
		float points1 = spring.getBean("points1", float.class);
		System.out.println("points:" + points1);
		float points2 = spring.getBean("points2", float.class);
		System.out.println("points:" + points2);
		float points3 = spring.getBean("points3", float.class);
		System.out.println("points:" + points3);
		float points4 = spring.getBean("points4", float.class);
		System.out.println("points:" + points4);
		float points5 = spring.getBean("points5", float.class);
		System.out.println("points:" + points5);
		float points6 = spring.getBean("points6", float.class);
		System.out.println("points:" + points6);
		float points7 = spring.getBean("points7", float.class);
		System.out.println("points:" + points7);
		float points8 = spring.getBean("points8", float.class);
		System.out.println("points:" + points8);
		System.out.println("***************CHAR***************       ");
		char start = spring.getBean("start", char.class);
		System.out.println("start:" + start);
		char stop = spring.getBean("stop", char.class);
		System.out.println("stop:" + stop);
		char upper = spring.getBean("upper", char.class);
		System.out.println("upper:" + upper);
		char lower = spring.getBean("lower", char.class);
		System.out.println("lower:" + lower);
		char star = spring.getBean("star", char.class);
		System.out.println("star:" + star);
		char cap = spring.getBean("cap", char.class);
		System.out.println("cap:" + cap);
		char equals = spring.getBean("equals", char.class);
		System.out.println("equals:" + equals);
		char add = spring.getBean("add", char.class);
		System.out.println("add:" + add);
		char minus = spring.getBean("minus", char.class);
		System.out.println("minus:" + minus);
		System.out.println(" *************CLASSES************           ");

		Animal animal = spring.getBean(Animal.class);
		System.out.println(animal);
		String animal1 = animal.gender();
		System.out.println("gender:" + animal1);
		Bicycle bicycle = spring.getBean(Bicycle.class);
		System.out.println(bicycle);
		String ref = bicycle.ownername();
		System.out.println("ownername:" + ref);
		Bird bird = spring.getBean(Bird.class);
		System.out.println(bird);
		String ref2 = bird.gender();
		System.out.println("gender:" + ref2);
		Bottel bottel = spring.getBean(Bottel.class);
		System.out.println(bottel);
		String ref3 = bottel.color();
		System.out.println("color is:" + ref3);
		Charger charger = spring.getBean(Charger.class);
		System.out.println(charger);
		String ref4 = charger.belongsto();
		System.out.println("belongsto:" + ref4);
		Exam exam = spring.getBean(Exam.class);
		System.out.println(exam);
		int ref5 = exam.totalstudents();
		System.out.println("totalstudents:" + ref5);
		Flower flower = spring.getBean(Flower.class);
		System.out.println(flower);
		String ref6 = flower.usedfor();
		System.out.println("usedfor:" + ref6);
		Function function = spring.getBean(Function.class);
		System.out.println(function);
		String ref7 = function.purpose();
		System.out.println("purpose:" + ref7);
		Glass glass = spring.getBean(Glass.class);
		System.out.println(glass);
		String ref8 = glass.color();
		System.out.println("color:" + ref8);
		HandBag handBag = spring.getBean(HandBag.class);
		System.out.println(handBag);
		String ref9 = handBag.usedfor();
		System.out.println("usedfor:" + ref9);
		Oil oil = spring.getBean(Oil.class);
		System.out.println(oil);
		String ref11 = oil.fuel();
		System.out.println("fuel:" + ref11);
		Sim sim = spring.getBean(Sim.class);
		System.out.println(sim);
		String ref12 = sim.mobile();
		System.out.println("phone:" + ref12);
		Pets pets = spring.getBean(Pets.class);
		System.out.println(pets);
		String ref13 = pets.location();
		System.out.println("location:" + ref13);
	}

}
